- name: AWS ECR
  # You may pin to the exact commit or the version.
  # uses: kciter/aws-ecr-action@79255b7c5aa03dbf6d7c46cff2bfd049874cd98d
  uses: kciter/aws-ecr-action@v4
  with:
    access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
    secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    # AWS Account ID
    account_id: 720291373173
    # Name of your ECR repository
    repo: fantasy-baseball-prod
    region: us-east-1
    tags: # optional, default is latest
    # Name of Dockerfile to use