- name: Login to ECR
  id: ecr
  uses: rahulrkr08/gh-aws-deploy@v3
  with:
    aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
    aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    aws_region: ${{ secrets.AWS_REGION }}
    image: 720291373173.dkr.ecr.us-east-1.amazonaws.com/fantasy-baseball-prod:latest